version: '2'
services:
    passerelle-app:
        image: passerelle
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://passerelle-mysql:3306/passerelle?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://passerelle-elasticsearch:9200
        ports:
            - 8082:8082
    passerelle-mysql:
        extends:
            file: mysql.yml
            service: passerelle-mysql
    passerelle-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: passerelle-elasticsearch
